CREATE DATABASE `debijenkorf` /*!40100 COLLATE 'utf8_general_ci' */;
CREATE USER 'debijenkorf'@'%' IDENTIFIED BY 'M8uh4S1DvC';
GRANT USAGE ON *.* TO 'debijenkorf'@'%';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `debijenkorf`.* TO 'debijenkorf'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;